name: Lint

on:
  push:
    branches:
      - main
      - ci
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install clang-format

    - name: Lint source code
      run: |
        clang-format -i ../../Code/src/*.c
        clang-format -i ../../Code/tests/*.c
