name: Test

on:
  push:
    branches:
      - main
      - ci
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install -qq build-essential expect sudo ccache
        sudo apt-get -y install clang-format make check lcov gcovr
        sudo apt install -y glibc-source gcc-arm-none-eabi
        sudo apt-get -y update
        sudo apt-get -y upgrade

    - name: Build tests
      run: make tests -C Code/

    - name: Run tests
      run: |
        chmod 777 Code/build/tri_tests
        ./Code/build/tri_tests
